create table if not exists users(
  userid varchar(40) NOT NULL,
  password varchar(100) NOT NULL,
  isadmin TINYINT  NOT NULL,
  email varchar(255)  NULL,
  phone varchar(20)  NULL,
  state char(1) NOT NULL,
  regtime varchar(20) NOT NULL,
  memo varchar(255)  NULL
);

insert into users values('admin', 'YWRtaW5fYWRtaW4=', 1, 'admin@163.com', '13888888888', 1, '2016-08-08 00:00:00', 'admin');

create table if not exists userrole(
  userid varchar(40) NOT NULL,
  roleid integer NOT NULL
);

create table if not exists resources(
  id integer NOT NULL,
  name varchar(20) NOT NULL,
  type char(1) NOT NULL,
  method varchar(100)  NULL,
  url varchar(100)  NULL,
  pid integer NOT NULL,
  iconcls varchar(20)  NULL,
  path varchar(100) NOT NULL,
  flag char(1) NOT NULL
);

create table if not exists role(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  name varchar(20) NOT NULL
);

create table if not exists roleres(
  roleid integer NOT NULL,
  resid integer NOT NULL
);

create table if not exists logs(
 	id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	operator varchar(20) NOT NULL, 
	ip varchar(40) NOT NULL, 
	time varchar(40) NOT NULL, 
	operation varchar(20) NOT NULL, 
	memo varchar(100) NOT NULL
);